### PR TITLE
Rtgov 360

### PR DESCRIPTION
**Pull request by mclay**

### CODE REVIEW

**Comment by objectiser** [comment]
Nearly - but now the button has been moved above the message panel. Could you move the button back to its previous location, with the text to the button's right (with a small gap)?

Also I found that when I pressed the button first time the UI was started up, it resubmitted the mesage (as I just sent the same erroneous message), but it didn't show any resubmission details. However when I pressed the button again, it resubmitted the message and then showed the details - have you seen this behaviour?

**Comment by mclay** [comment]
really? on my machine/browser (chrome) it's still below the message box. no
during my test's the resubmit worked from the first time and toggles
between success and failure with tooltip.

**Comment by objectiser** [comment]
I was using firefox - so I'll try chrome to see if it is different.

I was testing in eap, so its possible it is behaving differently to the mock server - I'll try both to see if I can get more info.

**Comment by objectiser** [comment]
Firstly the layout - I've used firefox and chrome both with eap and dev server, and the button is above the message area on both. The only difference is that on firefox the button is next to the Message Details text, whereas on chrome it is on the right hand side of the page.

In terms of the resubmission details, have also confirmed it does not appear on first resubmit after server started - both on firefox and chrome. Also you mentioned the failure with tooltip - I don't get a tooltip?

**Comment by objectiser** [comment]
Just had a thought - could you rebase on current master, as I did a change from using sramp widgets to ones in overlord-commons - they should be the same widgets, but just to make sure nothing has changed. If you could then retry after rebasing, to see if you get the layout issues.

**Comment by mclay** [comment]
i will do that

**Comment by mclay** [comment]
sorry i can't reproduce it pls find the two screenshot's attached.

sc1 git log is

commit c43f966b65a20968cfadcb1aca0d9b7f0a4e7d1a
Author: Michael Clay clay@codeworkz.at
Date:   Thu Feb 13 11:59:58 2014 +0000
    RTGOV-360: Move the 'resubmit' fields closer to the resubmit button
    RTGOV-350 Provide a JMX based SwitchYard service provider implementation
commit 0292b4b76be00d13d89f70c5acaee2a6b7f97371
Author: Michael Clay clay@codeworkz.at

```
truncate resubmitErrorMessage
```

commit e1c286752fa5584207e16cb3bbb026f8b7ef935b
Author: Michael Clay clay@codeworkz.at

```
RTGOV-332 Record message resubmission details against situation. Add
```

UserContext and Interceptor binding. Add resubmit info fields to
SituationDetails page

commit 096e8b5d200bb881ddfdf351457257406930b8c1
Author: Gary Brown gary@brownuk.com

```
Update README.md
```

commit b04312d9c76b7d7e83d8a82458f0be459824a689
Merge: b2a6035 46eb261
Author: Gary Brown gary@brownuk.com

```
Merge pull request #8 from objectiser/testfix
```

sc2 git log is

commit 7b303781ab44713f3bd0e04a8f433d67873063ba
Author: Michael Clay clay@codeworkz.at

```
RTGOV-360: Move the 'resubmit' fields closer to the resubmit button
```

commit 5e93b3d5f8a7080c99c8563c34f0894f89de8c20
Author: Michael Clay clay@codeworkz.at

```
RTGOV-359 Truncate resubmit failure message to avoid h2 column length
```

limitation

commit a0df01e0decdbd599b705b2db7c7f41de90d04c5
Merge: e1c2867 6a56a39
Author: Gary Brown gary@brownuk.com

```
Merge pull request #10 from objectiser/RTGOV-361
```

commit 6a56a39c506d224f002534293b0abe14ba016356
Author: objectiser gary@brownuk.com

```
RTGOV-361 Switch to using gwt/bootstrap widgets from overlord-commons
```

instead of sramp project

commit e1c286752fa5584207e16cb3bbb026f8b7ef935b
Author: Michael Clay clay@codeworkz.at

```
RTGOV-332 Record message resubmission details against situation. Add
```

UserContext and Interceptor binding. Add resubmit info fields to
SituationDetails page

**Comment by objectiser** [comment]
Ok, will raise a separate jira for this, so we can investigate further.

Did you manage to test the first resubmit, after server start (when deployed to EAP)?

Also, where is the tooltip anchored? as I could find it on the eap or dev server - and is not clear on the images you sent?

**Comment by mclay** [comment]
ok could you pls accept RTGOV-360 and i will fix the remaining issue in the
new jira.  no i haven't looked into the 'first resubmit' issue since i dont
know how to setup/configure eap (fsw) to test message resubmit's - any
hint's or instruction's on this?.
The tooltip (title) is anchored on the resubmit details label.

**Comment by objectiser** [comment]
Thanks Michael - I'll create jiras for the layout and 'first resubmit' issue. Tooltip worked fine - not sure why I didn't see it before.

**Pull request merged**
