### PR TITLE
Rtgov 330

### PR DESCRIPTION
**Pull request by mclay**

### CODE REVIEW

**Comment by mclay** [comment]
Summary of Changes:
- add @RequiresAuthentication method level annotation + Rule based interceptor for AuthenticationAdapter (RolesRequiredRule)
- added Login page
- new Operations/Buttons for assign/deassign for authenticated User + resolutionState update operations (start,stop,resolve)

**Comment by EricWittmann** [comment]
So what you've done for authentication makes a lot of sense for some Errai applications but unfortunately I don't think it's what we want for rtgov.  What we would like to have for authentication is to use classic webapp authentication.  In fact, the EAP61 version of this application _already_ includes authentication (via the shared Overlord SSO mechanism).  So I think we should remove the Login related work from this PR and replace it with standard webapp security.

I can do this easily on master if you want, or you can try adding it yourself by taking a look at the following examples:

1) Configure the Mock Runtime (Jetty) to use a SecurityHandler:  https://github.com/EricWittmann/apiman/blob/master/apiman-dt/apiman-dt-test/apiman-dt-test-api/src/main/java/org/overlord/apiman/dt/test/server/DtApiTestServer.java#L185-L215

2) Configure the base web.xml to include security constraints and BASIC auth info:  https://github.com/EricWittmann/s-ramp/blob/master/s-ramp-server/src/main/webapp/WEB-INF/web.xml#L30-L47

3) In SituationsService, get the current username from the current ServletRequest (available via the RpcContext) instead of from the AuthSubject

This should result in the removal (unfortunately) of the custom annotation, as well as the login page.

Does this make sense?  I'm happy to discuss further.

**Comment by mclay** [comment]
thank's for the feedback and yes it's absolutely ok for me - should i
track/resolve the Authentication/Configuration change in another Jira or
include it in RTGOV-330?

**Comment by EricWittmann** [comment]
Great!  Please let me know if you run into any problems.  I don't think we need a separate Jira for the authentication change.

**Comment by mclay** [comment]
done pls review

**Comment by EricWittmann** [comment]
Looks great!  Thanks very much.  I haven't tested it yet on FSW6 but I will try to do that today.  I don't have the experience with rtgov that Gary has, so we'll see how I do.  :)

**Pull request merged**
