### PR TITLE
RTGOV-331 Enable user to filter situations based on their resolution sta...

### PR DESCRIPTION
**Pull request by mclay**
...tus

### CODE REVIEW

**Comment by objectiser** [comment]
Hi Michael - thanks for submitting this pull request.

However when I try to build, I get a problem with a missing class ResolutionStateListBox, which I believe should be in the overlord-rtgov-ui-war, package org.overlord.rtgov.ui.client.local.pages.situations.

Also was wondering why the EntityManagerFactoryDelegate is being created in the RTGovRepositoryTest, as it does not appear to be doing anything?

Finally, was wondering whether a default value should be returned from SituationSummaryBean if no property is found - probably the Open state?

**Comment by mclay** [comment]
hi, sorry i somehow forgot to add this File - just added the missing files.

the purpose of EntityManagerFactoryDelegate is to provide (re)use and share the same EntityManager instance (think transaction) between the test method's in RTGovRepositoryTest and the to be tested method's in RTGovRepositoryTest.   This is required because RTGovRepository incorporates a (for me unusual) Transaction Demarcation Behavior which doesn't allow it to participate in already running transaction's (read) and therefore effectively makes it behave 'auto-commit'-like (write). 

SituationSummaryBean default value: done that.

**Comment by objectiser** [comment]
Sorry Michael, some more items:
1) When viewing the 'Status' dropdown, it shows the text for Any, Open and Resolved ok, but the others are shown in the form "!!!resolutionState.confirmed!!!" - this is the case when running "mvn install -Prun" and also when deployed to EAP.

2) When running "mvn install -Prun", selecting the different items in the Status dropdown filter does not affect the list of situations displayed. E.g. in the mock situation data there is an 'open' situation - however when selecting the Open status in the dropdown, all the situations are still displayed.

3) The default value for status is only returned if there is no properties map - however if the map exists with no 'resolutionState' value, then a null will still be returned.

**Comment by mclay** [comment]
hi, just fixed item 1 and 3 - are you sure about item 2? because the MockSituationsServiceImpl hasn't ANY filter logic for ANY of the existing filter/search fields up until now i.e. it always returns the same list regardless of any existing filter e.g. severity,type or timestamp. do you mean that we should start implementing this filter logic beginning with RTGOV-331?

**Comment by objectiser** [comment]
Ok forget item 2 :)

**Comment by mclay** [comment]
done. thanks for the review!

**Comment by objectiser** [comment]
Merged - thanks Michael.

**Pull request closed without merging**
